name: API Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ai_saas_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Generate Prisma Client
        run: pnpm -F @sb/api prisma:generate
      - name: Run migrations
        run: pnpm -F @sb/api db:migrate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ai_saas_test
      - name: Seed database
        run: pnpm -F @sb/api db:seed
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ai_saas_test
      - name: Test with coverage
        run: pnpm -F @sb/api test:cov
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ai_saas_test
          RATE_LIMIT_TTL: '2'
          RATE_LIMIT_LIMIT: '3'



